export function validEnvironment(
  overrides: Partial<NodeJS.ProcessEnv> = {},
): NodeJS.ProcessEnv {
  return {
    NODE_ENV: "test",
    LOG_LEVEL: "error",
    SERVICE_NAME: "oscar-payment-gateway-test",
    API_HOST: "127.0.0.1",
    API_PORT: "3000",
    SHUTDOWN_TIMEOUT_MS: "5000",
    MONGODB_URI: "mongodb://127.0.0.1:27017/oscar_test?replicaSet=rs0",
    MONGODB_REPLICA_SET: "rs0",
    MONGODB_CONNECT_TIMEOUT_MS: "5000",
    REDIS_URL: "redis://127.0.0.1:6379",
    REDIS_CONNECT_TIMEOUT_MS: "5000",
    QUEUE_PREFIX: "oscar-test",
    ADMIN_JWT_CURRENT_KEY_ID: "test-current-v1",
    ADMIN_JWT_CURRENT_SECRET: "test-admin-jwt-current-secret-value-0001",
    ADMIN_JWT_PREVIOUS_KEY_ID: "",
    ADMIN_JWT_PREVIOUS_SECRET: "",
    MERCHANT_STEP_UP_SECRET: "test-merchant-step-up-secret-value-0001",
    ADMIN_ACCESS_TTL_SEC: "600",
    ADMIN_REFRESH_TTL_SEC: "604800",
    MERCHANT_STEP_UP_TTL_SEC: "300",
    WALLET_NETWORK_ALLOWLIST:
      '{"ethereum-mainnet":"mainnet","ethereum-sepolia":"testnet"}',
    RPC_PROVIDER_CATALOG:
      '{"rpc-test-a":{"operatorId":"operator-a","url":"http://127.0.0.1:18545"},"rpc-test-b":{"operatorId":"operator-b","url":"http://127.0.0.1:28545"}}',
    RPC_REQUEST_TIMEOUT_MS: "5000",
    PAYMENT_EXPIRY_MIN_SEC: "300",
    PAYMENT_EXPIRY_MAX_SEC: "7200",
    PAYMENT_EXPIRY_DEFAULT_SEC: "900",
    IDEMPOTENCY_TTL_SEC: "86400",
    PAYMENT_CREATE_RATE_LIMIT_PER_MINUTE: "30",
    INGESTION_HMAC_CURRENT_KEY_ID: "test-ingest-v1",
    INGESTION_HMAC_CURRENT_SECRET: "test-ingestion-hmac-current-secret-0001",
    INGESTION_HMAC_PREVIOUS_KEY_ID: "",
    INGESTION_HMAC_PREVIOUS_SECRET: "",
    INGESTION_TIMESTAMP_SKEW_SEC: "300",
    INGESTION_NONCE_TTL_SEC: "600",
    INTERNAL_INGESTION_BASE_URL: "http://127.0.0.1:3000",
    WATCHER_POLL_INTERVAL_MS: "2000",
    WATCHER_BATCH_SIZE: "10",
    WATCHER_REGISTRY_REFRESH_SEC: "30",
    WATCHER_INITIAL_LOOKBACK_BLOCKS: "0",
    WEBHOOK_HMAC_CURRENT_KEY_ID: "test-webhook-v1",
    WEBHOOK_HMAC_CURRENT_SECRET: "test-webhook-hmac-secret-32-bytes-ok!!",
    WEBHOOK_HMAC_PREVIOUS_KEY_ID: "",
    WEBHOOK_HMAC_PREVIOUS_SECRET: "",
    SANCTIONS_STATIC_LIST:
      '{"listVersion":"test-v1","addresses":["0xD78523784b3A8e5c21D026eE7Fe405C39D1542ac"]}',
    SCREENING_CACHE_TTL_SEC: "604800",
    ...overrides,
  };
}
